/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sample_test_Library */

#ifndef _Included_com_sample_test_Library
#define _Included_com_sample_test_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sample_test_Library
 * Method:    Initiator
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_sample_test_Library_Initiator
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
